# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20170910_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u535a\u5ba2\u8bc4\u8bba', 'verbose_name_plural': '\u535a\u5ba2\u8bc4\u8bba'},
        ),
    ]
